/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.primitives.Doubles;

import java.util.ArrayList;
import java.util.List;

/**
 * To start the application:
 * ./gradlew build
 * java -jar ./HW01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l HW01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
public class HelloOtus {
    public static void main(String... args) {
        List<Double> example = new ArrayList<>();
        example.add(100.1d);
        example.add(0.1d);
        example.add(14.7d);
        example.add(20.0d);
        example.add(99.9d);

        double[] doubleArr = Doubles.toArray(example);

        System.out.println(Doubles.max(doubleArr));
        System.out.println(Doubles.min(doubleArr));
        System.out.println(Doubles.contains(doubleArr, 100.0d));
        System.out.println(Doubles.contains(doubleArr, 14.7d));
    }
}
